### ISSUE TITLE
The recognition lexicon

### ISSUE THREAD

**Issue by xudh777** [Bobo-y/number_detection_recognition#2]
On the format of recognition data, you just say to like to the format of  MJSynth data,  and I want to know in your data, How a dictionary is defined, Your target is 11 in length and has 11 characters to recognize, and your lexicon will have the length of 11^11???  It is too long, I doubt if my understanding is correct.
Please give me help

**Comment by Bobo-y** [comment]
@xudh1991 hi, for MJSynth data, the lexicon is a file  that  records the characters on each image, as follow

![image](https://user-images.githubusercontent.com/9928596/69426681-bdc84500-0d68-11ea-9537-358aa0d3ebc7.png)

for annotation_train.txt or annotation_test.txt , their format as follow

![image](https://user-images.githubusercontent.com/9928596/69426917-519a1100-0d69-11ea-9137-fc07556dad0d.png)
Contains the path of each image  and the line number of the characters on this image in the lexicon file

**Comment by xudh777** [comment]
I've downloaded  MJSynth data,  And know the format, But in your project,  the goal is to identify numbers that are 11 in length, according to the format of MJSynth data,  You should list all the possibilities to form a lexicon file, and all the possibilities is the length of 11^11 = 285311670611, 
like:
1_00000000000.jpg 0
2_00000000001.jpg 1
3_00000000002.jpg 2
4_00000000003.jpg 3
5_00000000004.jpg 4
6_00000000005.jpg 5
......
285311670611_99999999999.jpg 285311670610

It is too long, I wonder if you do this.

**Comment by xudh777** [comment]
I've downloaded  MJSynth data,  And know the format, But in your project,  the goal is to identify numbers that are 11 in length, according to the format of MJSynth data,  You should list all the possibilities to form a lexicon file, and all the possibilities is the length of 11^11 = 285311670611, 
like:
1_00000000000.jpg 0
2_00000000001.jpg 1
3_00000000002.jpg 2
4_00000000003.jpg 3
5_00000000004.jpg 4
6_00000000005.jpg 5
......
285311670611_99999999999.jpg 285311670610

It is too long, I wonder if you do this.

**Comment by Bobo-y** [comment]
@xudh1991 I think you misunderstood it. It just records the characters to be recognized in each picture. I just guarantee that the length of the numbers in each picture is 11, and the numbers are randomly generated (the length is less than 11, which is OK, and cannot be greater than 11). It does not need to arrange the numbers completely.
