### ISSUE TITLE
May I ask what type of partial dataset you identify？？？

### ISSUE THREAD

**Issue by shihuangxiong** [Bobo-y/number_detection_recognition#3]
May I ask what type of partial dataset you identify？？？

**Comment by yl305237731** [comment]
For location, randomly generated numbers are added to any position of the image. For recognition, the numbers are randomly added to the image and then cropped.

**Comment by Bobo-y** [comment]
@shihuangxiong For location, randomly generated numbers are added to any position of the image. For recognition, the numbers are randomly added to the image and then cropped.

**Comment by shihuangxiong** [comment]
Thank you for you reply.I am now working on my graduate project,and you code is very helpful to me. Can we replace the dataset with continuous recognition of Chinese and letter?


________________________________
发件人: lulu <notifications@github.com>
发送时间: 2019年12月1日 12:46
收件人: yl305237731/number_detection_recognition <number_detection_recognition@noreply.github.com>
抄送: shihuangxiong <shihuangxiong@outlook.com>; Author <author@noreply.github.com>
主题: Re: [yl305237731/number_detection_recognition] May I ask what type of partial dataset you identify？？？ (#3)


For location, randomly generated numbers are added to any position of the image. For recognition, the numbers are randomly added to the image and then cropped.

―

**Comment by Bobo-y** [comment]
@shihuangxiong Of course, you just need to change the dataset. Nothing needs to be changed for location, and some configuration needs to be changed for recognition.
