### ISSUE TITLE
please HELP me

### ISSUE THREAD

**Issue by WqxLoveCoding** [Bobo-y/number_detection_recognition#4]
![image](https://user-images.githubusercontent.com/57825815/118499411-7ce09f00-b759-11eb-89d9-dcc1ec3ca148.png)
请问这三个文件的具体格式是怎样的？我如何准备自己的数据集？
What is the specific format of these three files? How do I prepare my own dataset?

**Comment by Bobo-y** [comment]
@WqxLoveCoding  

annotation_train.txt  里面每一行构成如下：
图片名 + 空格 + 该图片的字符标签在lexicon.txt所在的行
115_Lube_45484.jpg 45484
113_accommodatingly_613.jpg 613
112_CARPENTER_11682.jpg 11682
111_REGURGITATING_64100.jpg 64100

annotation_val.txt 同上

lexicon.txt 中每一行是一张图片中字符的标签，如

aa
bb
abc
asd
